DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users ( 
	name			TEXT NOT NULL PRIMARY KEY,
	role			TEXT NOT NULL,
	age			INTEGER NOT NULL,
	state			TEXT NOT NULL
);

CREATE TABLE Categories ( 
	name			TEXT NOT NULL PRIMARY KEY,
	description		TEXT NOT NULL,
	owner			TEXT FOREIGN KEY REFERENCES User(name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Products ( 
	name			TEXT NOT NULL,
	SKU			INTEGER NOT NULL PRIMARY KEY,
	category		TEXT FOREIGN KEY REFERENCES Categories(name) ON DELETE CASCADE ON UPDATE CASCADE,
	price			MONEY NOT NULL
);

CREATE TABLE Cart ( 
	customer		TEXT FOREIGN KEY REFERENCES Users(name) ON DELETE CASCADE ON UPDATE CASCADE,
	product			TEXT FOREIGN KEY REFERENCES Products(name) ON DELETE CASCADE ON UPDATE CASCADE,
	quantity		INTEGER NOT NULL
);